[package]
name = "ardeck"
version = "0.0.2"
description = "ARDeck Control Center"
authors = ["akurakuu", "sekurosu-daimajin"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-hide", "window-start-dragging", "window-close", "window-minimize", "window-unminimize", "window-unmaximize", "window-show", "window-maximize", "system-tray", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
window-shadows = "0.2.2"
serialport = {version = "4.3.0", features = ["serde"] }
# once_cell = "1.19.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
